### ISSUE TITLE
Corrupted JSON response when producing a message

### ISSUE THREAD

**Issue by snezhkoigor** [Vinelab/bowler#46]
Hi. I have some problem with row 123 in file Producer.php

echo ' [x] Data Package Sent to ', $this->exchangeName, ' Exchange!', "\n";

When I'm trying send something to frontend after $producer->send(...) every time I have extra text in response.

My case - I send message to RabbitMQ, generate uniq channel id and send channel to frontend.

**Comment by snezhkoigor** [comment]
`$job = new OptimizerPositioningRequestJob(
            $channel,
            [
                'stations' => $gas_stations,
                'way_points' => $way_points
            ]
        );
        $this->dispatch($job);

        return response()->json([
            'data' => [
                'channel' => $channel,
                'reference_points' => $through_cities,
                'way_points' => $way_points
            ]
        ], Response::HTTP_OK)`

In OptimizerPositioningRequestJob I send message, so response()->json has extra text

**Comment by snezhkoigor** [comment]
Now I've redeclared Producer class with method send

**Comment by KinaneD** [comment]
Sure, whenever a message is sent to the queue, a notification is printed in terminal. That is being returned along with your JSON response.
You should surround the function to send the message [`ob_start()`](http://php.net/manual/en/function.ob-start.php) and [`ob_end_clean()`](http://php.net/manual/en/function.ob-end-clean.php) to discard the output.
```php
ob_start();
$producer->send($exchange, $payload);
$ob_end_clean();
```

On a side note, please change the issue title to reflect what the actual issue is; to improve its discoverability for others.

Thanks.

**Comment by snezhkoigor** [comment]
Thank you so much!
